# This is a basic workflow to help you get started with Actions

name: Pytest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.9.5
        uses: actions/setup-python@v2
        with: 
         python-version: 3.9.5
      
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest


      - name: Install Chrome
        run:  sudo apt install google-chrome-stable
      
      - name: Start docker
        run: docker-compose up -d
      
      - name: Sleep for 45 seconds
        run: sleep 45s
        shell: bash


      - name: Test with pytest
        run:  pytest
      
      - name: Collect docker logs
        uses: jwalton/gh-docker-logs@v1
        with:
         dest: './logs'
      
      - name: Archive execution artifacts
        uses: actions/upload-artifact@v2
        with:
         name: docker-logs
         path: ./logs

      
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
